### ISSUE TITLE
Seperate tests in folders

### ISSUE THREAD

**Issue by productiveme** [olexale/bdd_widget_test#12]
Greetings,

It would be ideal for us to have a folder structure to separate tests e.g.

```
test/
test/step/
test/bdd/
test/bdd/epic-name/test_name.feature
```

which would then generate the `test/bdd/epic_name/test_name_test.dart` but referencing the shared steps at the `test/step/` folder?  

Could this be configured?

**Comment by olexale** [comment]
Hi,

Thanks, that's a great change request! It is possible to [configure](https://github.com/olexale/bdd_widget_test#i-dont-like-the-step-folder-name-how-can-i-change-it) that starting from version `1.0.3+1`.

For your case the following `build.yaml` config should work:
```yaml
targets:
  $default:
    builders:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: ../../step
        generate_for:
          - test/bdd/*/*.feature
```

Could you please try the latest version and check whether it works for you?

Regards,
Oleksandr
