### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by olexale** [olexale/bdd_widget_test#20]
It would be nice to have some sort of configuration file to share settings between various packages in large projects. It can be something like `bdd_config.yaml` with the content:
```yaml
include: package:some_common_package/bdd_config.yaml

stepFolderName: ../test/step # this trick is required to share steps between widget and integration tests
# testMethodName: customTestMethodName
externalSteps:
  - package:bdd_widget_test/step/i_see_text.dart
  - package:bdd_widget_test/step/i_dont_see_text.dart
...
```
