### ISSUE TITLE
Add a suffix for the test file to be able to ignore them in the linter.

### ISSUE THREAD

**Issue by lsaudon** [olexale/bdd_widget_test#47]
It's not possible to make `*.g.dart` files, but it would be possible to make `*_feature_test.dart` so you can ignore the files in the linter.

**Comment by olexale** [comment]
Hey, thanks for your proposition.
I'd expect you don't mess your feature tests with regular unit tests? If so, assuming you have some folder (let's say you call it `feature`), why don't you filter feature tests in `analysis_options.yaml` like that:
```yaml
analyzer:
  exclude:
    - '**/feature**/*_test.dart'
```
