### ISSUE TITLE
Integration tests with hooks

### ISSUE THREAD

**Issue by hungcaovn** [olexale/bdd_widget_test#82]
Hi, I am using bdd_widget_test and I want to add hooks in integration_test folder (instead of test folder). How could I archive that?

**Comment by olexale** [comment]
Hey @hungcaovn,

That's not possible with the current latest stable version. Would you please help me test this feature?
To test it, change the dependency in your `pubspec.yaml` file as follows:
```yaml
dev_dependencies:
  bdd_widget_test:
    git:
      url: https://github.com/olexale/bdd_widget_test.git
      ref: feature/absolute_path_to_steps
```

And then update the `build.yaml` file like that:
```yaml
          hookFolderName: integration_test/bdd_hooks
          stepFolderIsUnderTestFolder: false
```

If everything is correct, you'll see hooks under the `integration_test` folder. Looking forward to hearing feedback from you!

**Comment by hungcaovn** [comment]
@olexale : I can confirm that it works! That's great, please make it release please

**Comment by olexale** [comment]
Added in `1.7.6`. I renamed the parameter to `relativeToTestFolder` as this name better shows what it controls. You may expect this version to be available on pub.dev soon.

**Comment by hungcaovn** [comment]
@olexale : Could you please double check ver 1.7.6. I tried and found that it created integration_test/bdd_hooks in test folder. The one from feature/absolute_path_to_steps works perfectly but the official version does not work the same

**Comment by olexale** [comment]
@hungcaovn, I see that all the required changes are included in the latest build. Could you create a small repository reproducing the issue so I can take a closer look?

**Comment by hmai-rm** [comment]
Hi @olexale,

I configured my `build.yaml` to use hooks like this:

```
targets:
  $default:
    builders:
      bdd_widget_test|featureBuilder:
        options:
          addHooks: true
          relativeToTestFolder: false
          stepFolderName: integration_test/steps 
          hookFolderName: integration_test/bdd_hooks <-- this line
        generate_for:
          - integration_test/**
```

Then the output test file will import the hook using backslashes instead of slashes, and that's why the import will not work:
```dart
import '..\..\integration_test/bdd_hooks\hooks.dart';
``` 

The correct statement should be:

```dart
import '../../integration_test/bdd_hooks/hooks.dart';
```

**Comment by hungcaovn** [comment]
@olexale : Check my screenshot. I am using v1.8.1. You can see the hooks.dart is in this path test/integration_test/bdd_hooks. It should be integration_test/bdd_hooks only

![Image](https://github.com/user-attachments/assets/37934a0e-14f2-4a1c-a4ff-86442d1bd847)

**Comment by olexale** [comment]
@hungcaovn, I still can not reproduce the problem. I add the following lines to `build.yaml`:
```yaml
          hookFolderName: integration_test/bdd_hooks
          relativeToTestFolder: false
          addHooks: true
```
of a sample project, and that's what I have:

<img width="386" alt="Image" src="https://github.com/user-attachments/assets/31f68eef-365e-4d6d-9a23-d674a33bd55f" />

Do you mind sharing the `build.yaml` you are using?
