### ISSUE TITLE
Absolute hook folder name on Windows

### ISSUE THREAD

**Issue by olexale** [olexale/bdd_widget_test#93]
Copied from https://github.com/olexale/bdd_widget_test/issues/82#issuecomment-2705617915

Hi @olexale,

I configured my `build.yaml` to use hooks like this:

```
targets:
  $default:
    builders:
      bdd_widget_test|featureBuilder:
        options:
          addHooks: true
          relativeToTestFolder: false
          stepFolderName: integration_test/steps 
          hookFolderName: integration_test/bdd_hooks <-- this line
        generate_for:
          - integration_test/**
```

Then the output test file will import the hook using backslashes instead of slashes, and that's why the import will not work:
```dart
import '..\..\integration_test/bdd_hooks\hooks.dart';
``` 

The correct statement should be:

```dart
import '../../integration_test/bdd_hooks/hooks.dart';
```

**Comment by olexale** [comment]
Hey @hmai-rm. I created a new issue for the problem you described, as it's clearly a new issue. 

I assume you are on windows. I don't have a PC to check, but I think I understand the problem. Would you mind checking the fix? Update the dependency like this:
```yaml
dev_dependencies:
  bdd_widget_test:
    git:
      url: https://github.com/olexale/bdd_widget_test.git
      ref: bugfix/absolute_path_hook_windows
```

Looking forward to your reply.
